config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  resources :messages

    $engine_manifests.each do |engine|
      eval("mount #{engine[:engine]} => '/', as: '#{engine[:route_as]}'")
    end

end

app/models/message.rb
class Message < ActiveRecord::Base
	# attributes
	# :id
	# :name
	# :content
	# :creator_id
	# :delivery_time
	# :is_disabled


	

	validates :name, presence: true, 
		uniqueness: { scope: :creator_id }
		
	validates :content, length: { maximum: 255 }
end

app/models/user.rb
class User < MultiDatabase::Connector

	connect_to("Test Database")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    
	def index
		@messages = Message.order(created_at: :desc)

	end

	def show
		@message = Message.where(id: params[:id]).first
	end

	def new
		@message = Message.new
	end

	def create
		# Params contains the message object so create new instance of object
		# on save successful save redirect to show action otherwise re-render new form with error messages
		@message= Message.new(message_params)

		if @message.save
			redirect_to @message
		else
			render 'new'
		end
	end

	def edit
		@message = Message.where(id: params[:id]).first
		@title = "test"

		if @message.blank?
			flash[:error] = "Unable to find requested Message"
			redirect_to action: :index
		end
	end

	def update
		@message = Message.where(id: params[:id]).first

		if @message.update(message_params)
			redirect_to @message
		else
			render 'edit'
		end
	end

	def destroy

		@message = Message.where(id: params[:id]).first
		if !@message.blank? and @message.destroy
			#no need to do anything at this time since we removed the message
		else
			flash[:error] = "Unable to perform requested Action"
		end
		redirect_to action: :index
	end

private
  # Include any private methods here that won't be accessible through routes

  def message_params
  	 params.require(:message).permit(:name, :content, :delivery_time)
  end

end # End of Controller

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/index.html.haml
%h1 Welcome To the Demo Site
%p Pins Links
%p Widgets 
%p Authentication

app/views/layouts/_load_engine_assets.haml
- folder = request[:controller].split("/").first

- $engine_manifests.each do |e|
  - if folder == e[:asset_folder]
    = stylesheet_link_tag "#{e[:asset_folder]}", media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag "#{e[:asset_folder]}", 'data-turbolinks-track' => true

app/views/layouts/_navigation.haml
%div#site_navigation
  %h4= "Notification Center"
  %div
    %p= link_to "View Messages", main_app.messages_path 

  - $engine_manifests.each do |e|
    %h4= e[:navigation_title]
    %div
      - e[:links].each do |link|
        %p= link_to link[:title], eval(link[:url])

    
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Message Demo</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= render partial: 'layouts/load_engine_assets' %> 
   
  <%= csrf_meta_tags %>
</head>
<body>



<div id="main-container" class="container-fluid">

  
  <div class="row">
    <div id="sidebar" class="col-xs-3">
      <!-- sidebar content -->
      <h3> SideBar Content </h3>

      <%= render partial: 'layouts/navigation' %>

	</div>
	<div id="content" class="col-xs-9">
		<%= render partial: 'shared/breadcrumb' %> 
	    <!-- flash errors content -->
        <div class="col-xs-12">
	       <% flash.each do |name, msg| -%>
	         <%= content_tag :div, msg, class: "alert alert-#{name}" %>
	       <% end -%>
	       <% flash = Array.new %>
	     </div>
        <!-- main content -->
        <%= yield %>
        
    </div>
  </div>
</div>
</body>

<footer><cite>Demo By Timothy Morton</cite></footer>
</html>

app/views/messages/_header_row.haml
%tr
	%th= :Name
	%th= :Content
	%th= :Active
	%th= "Delivery Time"
	%th= :Edit
	%th= :Destroy

app/views/messages/_message.haml
%tr
	%td= link_to message.name, message_path(message)
	%td= message.content
	%td= message.is_disabled ? "Yes" : "No"
	%td= I18n.l(message.delivery_time, format: :short)
	%td= link_to "Edit", edit_message_path(message)
	%td= link_to "Delete", message_path(message), method: :delete, data: {confirm: "Are you sure you want to delete #{message.name}?"}

app/views/messages/edit.haml
%nav
	- breadcrumb :edit_message, @message


%h3= "Edit Message - #{@message.name}"

%hr


= form_for @message,  url: { action: "update"}, html: { class: "form-horizontal"} do |f|

	%div.form-group
		= f.label :name, class: 'col-sm-2 control-label'
		%div.col-sm-10
			= f.text_field :name

	%div.form-group
		= f.label :delivery_time, class: 'col-sm-2 control-label'
		%div.col-sm-10
			= datetime_field(:message, :delivery_time, class: 'datetime_field')

	%div.form-group
		= f.label :content, class: 'col-sm-2 control-label'
		%div.col-sm-10
			= f.text_area :content, size: "60X12"
	%div.form-group
		%div.col-sm-offset-2.col-sm-10
			= f.submit "Create", class: 'btn btn-primary btn-lg'	

app/views/messages/index.haml
%nav
  - breadcrumb :messages


%h3="Messages"

%div.actionlist
  .item
    =link_to "New Message", new_message_path



%div.list
  %table.table-condensed
    = render partial: 'header_row'
    - @messages.each do |message|
      = render partial: 'message', object: message


%div.test
  = "This is a test of the css"
	

app/views/messages/new.haml
%nav
	- breadcrumb :new_message


%h3= "New Message"



= form_for @message,  url: { action: "create"}, html: { class: "form-horizontal"} do |f|

	%div.form-group
		= f.label :name, class: 'col-sm-2 control-label'
		%div.col-sm-10
			= f.text_field :name

	%div.form-group
		= f.label :delivery_time, class: 'col-sm-2 control-label'
		%div.col-sm-10
			= datetime_field(:message, :delivery_time, class: 'datetime_field')

	%div.form-group
		= f.label :content, class: 'col-sm-2 control-label'
		%div.col-sm-10
			= f.text_area :content, size: "60X12"
	%div.form-group
		%div.col-sm-offset-2.col-sm-10
			= f.submit "Create", class: 'btn btn-primary btn-lg'	

app/views/messages/show.haml
%nav
	- breadcrumb :message, @message, @title

%h2= "Displaying Message"

-if !@message.blank?
	%ul
		%li= "Name: #{@message.name}"
		%li= @message.delivery_time
		%li= @message.content
-else
	%strong.error="Message is not available for display may have been removed from system!"

app/views/shared/_breadcrumb.haml
%nav.navbar.navbar-default{role: "navigation"}
  %div.container
    %div.navbar-header
      - if current_page?(main_app.root_url)
        %ol.breadcrumb
          %li= "Home"
      - else
        = breadcrumbs  style: :bootstrap